server:
  port: 8087
  servlet:
    context-path: '/easysalao-authuser/'

spring:
  application:
    name: easysalao-authuser-service
  datasource:
    url: jdbc:mysql://localhost:3306/easysalao-authuser-v2?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: MYSQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://spfbumdg:C1jlwi0wvYGPaILFM0RmE6V1MntU9RUO@jaragua.lmq.cloudamqp.com/spfbumdg

logging:
  level:
    com.ead: INFO
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      userEvent: ead.userevent
      paymentEvent: ead.paymentevent
    queue:
     paymentEventQueue:
        name: ead.paymentevent.ms.authuser
        
authuser:
  refreshscope:
    name: Giovandro Fabio dos Santos
    
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health


resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        sliding-window-size: 30
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: TIME_BASED
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 80
  retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s