server:
  port: 8080

spring:
  application:
    name: easysalao-api-gateway
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://EASYSALAO-AUTHUSER-SERVICE
          predicates:
            - Path=/easysalao-authuser/**
        - id: easysalao-service
         # uri: lb://EASYSALAO-SERVICE
          uri: http://localhost:8762
          predicates:
            - Path=/easysalao-service/**
        - id: notification-service
          uri: lb://EAD-NOTIFICATION-SERVICE
          predicates:
            - Path=/ead-notification/**