server:
  port: 8762
  servlet:
    context-path: '/easysalao-service/'
spring:
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: easysalao-config-server
      username: configserver
      password: 'ead123cs'
  application:
    name: eaysalao-service
  datasource:
    url: jdbc:mysql://localhost:3306/eaysalao-v2?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: MYSQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

logging:
  level:
    com.eaysalao: INFO
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

eaysalao:
  broker:
    exchange:
      userEventExchange: eaysalao.userevent
    queue:
      userEventQueue:
        name: eaysalao.userevent.ms.eaysalao

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        sliding-window-size: 30
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: TIME_BASED
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 80
  retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s

easysalao:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${easysalao.serviceRegistry.username}:${easysalao.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

encrypt:
  key: p3s6v9y$B?E(H+MbQeThWmZq4t7w!z%C*F)J@NcRfUjXn2r5u8x/A?D(G+KaPdSg